<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>36df3e6f-ab3d-40c5-a455-1a0a3df4fbb7</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Controllers - Copy\**" />
    <Content Remove="Controllers - Copy\**" />
    <EmbeddedResource Remove="Controllers - Copy\**" />
    <None Remove="Controllers - Copy\**" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Azure.Messaging.ServiceBus" Version="7.20.2" />
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.12" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\AutoOps.Contracts\AutoOps.Contracts.csproj" />
  </ItemGroup>

</Project>
